# AUTOGENERATED — DO NOT EDIT.
#
# Generated from schema/design.v1.1.json by codegen/py.py.
# To regenerate: python codegen/py.py

# generated by datamodel-codegen:
#   filename:  design.v1.1.json
#   timestamp: 2026-05-24T22:22:57+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Hoop(BaseModel):
    """
    Embroidery hoop dimensions. Origin is the hoop center (0,0).
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    width_mm: Annotated[float, Field(alias="widthMm", ge=1.0, le=500.0)]
    """
    Hoop width in millimetres.
    """
    height_mm: Annotated[float, Field(alias="heightMm", ge=1.0, le=500.0)]
    """
    Hoop height in millimetres.
    """
    origin: Literal["center"] | None = "center"
    """
    Origin convention. v1 only supports center-origin (0,0 = hoop center).
    """


class Transform(BaseModel):
    """
    Element transform applied after geometry is defined in its local frame. Order: scale, then rotation around (0,0), then translation.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    x_mm: Annotated[float | None, Field(alias="xMm")] = 0
    """
    Translation along X in mm.
    """
    y_mm: Annotated[float | None, Field(alias="yMm")] = 0
    """
    Translation along Y in mm.
    """
    rotation_deg: Annotated[float | None, Field(alias="rotationDeg")] = 0
    """
    Rotation around origin in degrees.
    """
    scale_x: Annotated[float | None, Field(alias="scaleX", ge=0.01)] = 1
    """
    Scale factor along X. 1.0 = identity.
    """
    scale_y: Annotated[float | None, Field(alias="scaleY", ge=0.01)] = 1
    """
    Scale factor along Y.
    """


class ThreadIdentity(BaseModel):
    """
    Catalog identity for the thread. When present, the engine's PES writer uses the exact catalog entry instead of nearest-by-hex snapping. Hex remains authoritative for rendering.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    brand: str | None = None
    """
    Thread brand, e.g. 'Madeira', 'Brother'.
    """
    catalog_number: Annotated[str | None, Field(alias="catalogNumber")] = None
    """
    Brand's catalog identifier for the specific colour.
    """


class RailItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=2, min_length=2)]
    """
    [xMm, yMm].
    """


class Rail(RootModel[list[RailItem]]):
    root: Annotated[list[RailItem], Field(min_length=2)]


class RungItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=2, min_length=2)]


class Rung(RootModel[list[RungItem]]):
    root: Annotated[list[RungItem], Field(max_length=2, min_length=2)]
    """
    Two points [[xMm, yMm], [xMm, yMm]] defining one rung.
    """


class CenterlineItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=2, min_length=2)]


class SatinStitchSettings(BaseModel):
    """
    Stitch settings specific to satin columns. Defaults match stitch-defaults.json (the legacy parity fixture) so v1 imports of pre-spine docs are loss-free.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    thread_color_hex: Annotated[
        str, Field(alias="threadColorHex", pattern="^#[0-9a-fA-F]{6}$")
    ]
    """
    Thread colour as #RRGGBB.
    """
    thread: ThreadIdentity | None = None
    density_mm: Annotated[float | None, Field(alias="densityMm", ge=0.1, le=2.0)] = 0.4
    """
    Row spacing in mm.
    """
    density_auto: Annotated[bool | None, Field(alias="densityAuto")] = False
    """
    When true, scale density by column width (sqrt of width / 4mm reference).
    """
    max_stitch_mm: Annotated[
        float | None, Field(alias="maxStitchMm", ge=1.0, le=12.0)
    ] = 7.0
    """
    Maximum single stitch length in mm. Cap matches Brother PE700 acceptance.
    """
    min_stitch_mm: Annotated[
        float | None, Field(alias="minStitchMm", ge=0.1, le=5.0)
    ] = 0.5
    """
    Minimum single stitch length in mm. Below this the engine merges.
    """
    pull_comp_mm: Annotated[float | None, Field(alias="pullCompMm", ge=0.0, le=2.0)] = (
        0.2
    )
    """
    Perpendicular expansion in mm to offset thread-tension shrinkage.
    """
    push_comp_mm: Annotated[float | None, Field(alias="pushCompMm", ge=0.0, le=1.5)] = (
        0.0
    )
    """
    Parallel shortening in mm at column ends. 0 = engine auto-computes.
    """
    underlay: bool | None = True
    """
    Whether to generate underlay stitches before the satin pass.
    """
    underlay_type: Annotated[
        Literal["none", "center_run", "edge_run", "zigzag", "double_zigzag"] | None,
        Field(alias="underlayType"),
    ] = "center_run"
    """
    Underlay strategy.
    """
    underlay_density_mm: Annotated[
        float | None, Field(alias="underlayDensityMm", ge=0.5, le=20.0)
    ] = 2.0
    """
    Underlay row spacing in mm.
    """
    trim_after: Annotated[bool | None, Field(alias="trimAfter")] = False
    """
    Force a trim after this element finishes sewing.
    """


class SatinElement(BaseModel):
    """
    A satin column defined by two parallel rails (and optional rungs that override the engine's auto-pairing). Both rails are point lists in world-space mm, sampled the same direction.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["satin"]
    """
    Discriminator.
    """
    id: Annotated[str, Field(pattern="^[A-Za-z0-9_-]{1,64}$")]
    """
    Stable element id (kebab/snake case, 1-64 chars).
    """
    label: str | None = None
    """
    Optional human-readable label shown in the editor's Layers panel.
    """
    rails: Annotated[list[Rail], Field(max_length=2, min_length=2)]
    """
    Exactly two rails. Each rail is a polyline of [xMm, yMm] points.
    """
    rungs: list[Rung] | None = None
    """
    Optional explicit rungs (pairs of points joining the rails). When present, override the engine's automatic pairing.
    """
    transform: Transform | None = None
    stitch: SatinStitchSettings


class SplineStrokeElement(BaseModel):
    """
    A satin-style stroke band along a centerline. The engine extracts ±widthMm/2 rails from the centerline, then runs the same satin emitter used by SatinElement and border satin. Replaces the editor's client-side spline-stroke generator (lib/satin-gen.ts) under Phase C of the satin unification.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["splineStroke"]
    """
    Discriminator.
    """
    id: Annotated[str, Field(pattern="^[A-Za-z0-9_-]{1,64}$")]
    """
    Stable element id (kebab/snake case, 1-64 chars).
    """
    label: str | None = None
    """
    Optional human-readable label shown in the editor's Layers panel.
    """
    centerline: Annotated[list[CenterlineItem], Field(min_length=2)]
    """
    Ordered polyline of [xMm, yMm] points defining the stroke's centerline in world-space mm. The engine offsets ±widthMm/2 perpendicular to the local tangent to derive the two rails.
    """
    width_mm: Annotated[float, Field(alias="widthMm", ge=0.5, le=20.0)]
    """
    Total band width in mm — the distance between the two derived rails. Half is offset to each side of the centerline.
    """
    transform: Transform | None = None
    stitch: SatinStitchSettings


class StiqDesign(BaseModel):
    """
    Stiq design document v1.1 — additive superset of v1.0. Adds SplineStrokeElement (running-stitch and satin-band along a centerline). All v1.0 documents validate against v1.1 unchanged. See README §Versioning.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    schema_version: Annotated[
        str, Field(alias="schemaVersion", pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}$")
    ]
    """
    Dated snapshot the document was written against, e.g. '2026-05-25'. Engines accept any version within their supported window (typically the last 12 months) and migrate older docs at the API boundary. Distinct from the package semver — package versions govern the codegen surface, doc versions govern the wire format.
    """
    hoop: Hoop
    elements: list[
        Annotated[SatinElement | SplineStrokeElement, Field(discriminator="type")]
    ]
    """
    Ordered list of design elements. Stitch order follows array order (top-of-list = sewn first).
    """
