#!/usr/bin/env python3
"""
codegen/py.py — schema/design.v1.1.json → src/py/stiq_design_schema/__init__.py

Uses datamodel-code-generator to emit Pydantic v2 models with one
class per JSON Schema $def. The generated file is committed (see
README §Codegen) — CI enforces freshness via `python codegen/py.py`
+ `git diff --exit-code`.

Run from repo root:
    python codegen/py.py
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Codegen reads the LATEST minor revision of the v1 schema. v1.1 is an
# additive superset (SplineStrokeElement added) — Pydantic models are
# strictly extended; existing v1.0 docs still validate. Bump when v1.2
# lands.
SCHEMA = ROOT / "schema" / "design.v1.1.json"
OUT_DIR = ROOT / "src" / "py" / "stiq_design_schema"
OUT_FILE = OUT_DIR / "__init__.py"


def main() -> None:
    if not SCHEMA.exists():
        sys.exit(f"schema not found: {SCHEMA}")
    if shutil.which("datamodel-codegen") is None:
        sys.exit(
            "datamodel-codegen not on PATH. Install with: "
            "pip install 'datamodel-code-generator>=0.25.6'"
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Touch the package marker so hatchling picks it up even before
    # codegen runs once.
    (OUT_DIR / "py.typed").write_text("")

    cmd = [
        "datamodel-codegen",
        "--input", str(SCHEMA),
        "--input-file-type", "jsonschema",
        "--output", str(OUT_FILE),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--target-python-version", "3.10",
        "--use-schema-description",
        "--use-field-description",
        "--use-default",
        "--field-constraints",
        "--use-double-quotes",
        "--snake-case-field",
        "--allow-population-by-field-name",
        # discriminator is a JSON Schema 2020-12 keyword the generator
        # supports for Pydantic v2 discriminated unions.
        "--use-annotated",
        "--enum-field-as-literal", "all",
        "--use-standard-collections",
        # additionalProperties:false in schema → extra='forbid' on the
        # generated models. The engine-side payload-normalize layer
        # decides whether to relax this at the boundary.
        "--collapse-root-models",
    ]
    print(f"$ {' '.join(cmd)}")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        sys.exit(result.returncode)

    # Prepend an autogenerated header banner.
    text = OUT_FILE.read_text()
    banner = (
        "# AUTOGENERATED — DO NOT EDIT.\n"
        "#\n"
        "# Generated from schema/design.v1.1.json by codegen/py.py.\n"
        "# To regenerate: python codegen/py.py\n\n"
    )
    if not text.startswith("# AUTOGENERATED"):
        OUT_FILE.write_text(banner + text)

    print(f"wrote {OUT_FILE} ({OUT_FILE.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
