#!/usr/bin/env node
/**
 * codegen/ts.mjs — schema/design.v1.json → src/ts/index.ts
 *
 * Uses json-schema-to-typescript to emit a clean .ts file with all
 * named definitions exported as interfaces. Run via `npm run codegen:ts`.
 *
 * The generated file is committed (see README §Codegen). CI enforces
 * freshness with `npm run check:fresh` which regenerates and asserts
 * `git diff --exit-code` on src/.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
// Codegen reads the LATEST minor revision of the v1 schema. v1.1 is an
// additive superset of v1.0 (SplineStrokeElement added) so the emitted
// TS types are a strict superset — existing v1.0 consumers stay
// compile-clean. When v1.2 lands, bump this to design.v1.2.json.
const SCHEMA_PATH = resolve(ROOT, 'schema', 'design.v1.1.json')
const OUT_PATH = resolve(ROOT, 'src', 'ts', 'index.ts')

async function main() {
  const raw = await readFile(SCHEMA_PATH, 'utf8')
  const schema = JSON.parse(raw)

  // json-schema-to-typescript treats `discriminator` as an unknown
  // keyword. That's fine for type emission (it ignores it); ajv reads
  // it at runtime for validation. We strip it from the input we pass
  // to the compiler to keep the output clean.
  const cleaned = stripKeyword(schema, 'discriminator')

  const ts = await compile(cleaned, 'StiqDesign', {
    additionalProperties: false,
    bannerComment: [
      '/**',
      ' * AUTOGENERATED — DO NOT EDIT.',
      ' *',
      ' * Generated from schema/design.v1.1.json by codegen/ts.mjs.',
      ' * To regenerate: npm run codegen:ts',
      ' */',
    ].join('\n'),
    declareExternallyReferenced: true,
    enableConstEnums: false,
    strictIndexSignatures: true,
    style: { singleQuote: true, semi: false },
  })

  await mkdir(dirname(OUT_PATH), { recursive: true })
  await writeFile(OUT_PATH, ts, 'utf8')
  console.log(`wrote ${OUT_PATH} (${ts.length} bytes)`)
}

function stripKeyword(node, keyword) {
  if (Array.isArray(node)) return node.map(n => stripKeyword(n, keyword))
  if (node && typeof node === 'object') {
    const out = {}
    for (const [k, v] of Object.entries(node)) {
      if (k === keyword) continue
      out[k] = stripKeyword(v, keyword)
    }
    return out
  }
  return node
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
