/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Generated from schema/design.v1.1.json by codegen/ts.mjs.
 * To regenerate: npm run codegen:ts
 */

/**
 * A design element. Discriminated by `type`. v1.1 adds SplineStrokeElement on top of v1's SatinElement.
 */
export type Element = SatinElement | SplineStrokeElement

/**
 * Stiq design document v1.1 — additive superset of v1.0. Adds SplineStrokeElement (running-stitch and satin-band along a centerline). All v1.0 documents validate against v1.1 unchanged. See README §Versioning.
 */
export interface StiqDesign {
  /**
   * Dated snapshot the document was written against, e.g. '2026-05-25'. Engines accept any version within their supported window (typically the last 12 months) and migrate older docs at the API boundary. Distinct from the package semver — package versions govern the codegen surface, doc versions govern the wire format.
   */
  schemaVersion: string
  hoop: Hoop
  /**
   * Ordered list of design elements. Stitch order follows array order (top-of-list = sewn first).
   */
  elements: Element[]
}
/**
 * Embroidery hoop dimensions. Origin is the hoop center (0,0).
 */
export interface Hoop {
  /**
   * Hoop width in millimetres.
   */
  widthMm: number
  /**
   * Hoop height in millimetres.
   */
  heightMm: number
  /**
   * Origin convention. v1 only supports center-origin (0,0 = hoop center).
   */
  origin?: 'center'
}
/**
 * A satin column defined by two parallel rails (and optional rungs that override the engine's auto-pairing). Both rails are point lists in world-space mm, sampled the same direction.
 */
export interface SatinElement {
  /**
   * Discriminator.
   */
  type: 'satin'
  /**
   * Stable element id (kebab/snake case, 1-64 chars).
   */
  id: string
  /**
   * Optional human-readable label shown in the editor's Layers panel.
   */
  label?: string
  /**
   * Exactly two rails. Each rail is a polyline of [xMm, yMm] points.
   *
   * @minItems 2
   * @maxItems 2
   */
  rails: [
    [[number, number], [number, number], ...[number, number][]],
    [[number, number], [number, number], ...[number, number][]]
  ]
  /**
   * Optional explicit rungs (pairs of points joining the rails). When present, override the engine's automatic pairing.
   */
  rungs?: [[number, number], [number, number]][]
  transform?: Transform
  stitch: SatinStitchSettings
}
/**
 * Element transform applied after geometry is defined in its local frame. Order: scale, then rotation around (0,0), then translation.
 */
export interface Transform {
  /**
   * Translation along X in mm.
   */
  xMm?: number
  /**
   * Translation along Y in mm.
   */
  yMm?: number
  /**
   * Rotation around origin in degrees.
   */
  rotationDeg?: number
  /**
   * Scale factor along X. 1.0 = identity.
   */
  scaleX?: number
  /**
   * Scale factor along Y.
   */
  scaleY?: number
}
/**
 * Stitch settings specific to satin columns. Defaults match stitch-defaults.json (the legacy parity fixture) so v1 imports of pre-spine docs are loss-free.
 */
export interface SatinStitchSettings {
  /**
   * Thread colour as #RRGGBB.
   */
  threadColorHex: string
  thread?: ThreadIdentity
  /**
   * Row spacing in mm.
   */
  densityMm?: number
  /**
   * When true, scale density by column width (sqrt of width / 4mm reference).
   */
  densityAuto?: boolean
  /**
   * Maximum single stitch length in mm. Cap matches Brother PE700 acceptance.
   */
  maxStitchMm?: number
  /**
   * Minimum single stitch length in mm. Below this the engine merges.
   */
  minStitchMm?: number
  /**
   * Perpendicular expansion in mm to offset thread-tension shrinkage.
   */
  pullCompMm?: number
  /**
   * Parallel shortening in mm at column ends. 0 = engine auto-computes.
   */
  pushCompMm?: number
  /**
   * Whether to generate underlay stitches before the satin pass.
   */
  underlay?: boolean
  /**
   * Underlay strategy.
   */
  underlayType?: 'none' | 'center_run' | 'edge_run' | 'zigzag' | 'double_zigzag'
  /**
   * Underlay row spacing in mm.
   */
  underlayDensityMm?: number
  /**
   * Force a trim after this element finishes sewing.
   */
  trimAfter?: boolean
}
/**
 * Catalog identity for the thread. When present, the engine's PES writer uses the exact catalog entry instead of nearest-by-hex snapping. Hex remains authoritative for rendering.
 */
export interface ThreadIdentity {
  /**
   * Thread brand, e.g. 'Madeira', 'Brother'.
   */
  brand?: string
  /**
   * Brand's catalog identifier for the specific colour.
   */
  catalogNumber?: string
}
/**
 * A satin-style stroke band along a centerline. The engine extracts ±widthMm/2 rails from the centerline, then runs the same satin emitter used by SatinElement and border satin. Replaces the editor's client-side spline-stroke generator (lib/satin-gen.ts) under Phase C of the satin unification.
 */
export interface SplineStrokeElement {
  /**
   * Discriminator.
   */
  type: 'splineStroke'
  /**
   * Stable element id (kebab/snake case, 1-64 chars).
   */
  id: string
  /**
   * Optional human-readable label shown in the editor's Layers panel.
   */
  label?: string
  /**
   * Ordered polyline of [xMm, yMm] points defining the stroke's centerline in world-space mm. The engine offsets ±widthMm/2 perpendicular to the local tangent to derive the two rails.
   *
   * @minItems 2
   */
  centerline: [[number, number], [number, number], ...[number, number][]]
  /**
   * Total band width in mm — the distance between the two derived rails. Half is offset to each side of the centerline.
   */
  widthMm: number
  transform?: Transform
  stitch: SatinStitchSettings
}
